import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import static java.lang.Thread.sleep;

public class GoogleSearchTest {
    private static final String GOOGLE_MAIN_PAGE_URL = "https://www.google.com/" ;
    private String resultsStatsTextValue; // results of the search generated by a search engine website
    private WebDriver driver;
    private By resultVerifyLocator = By.id("result-stats"); // id for the  search results element
    private By textInputLocator = By.cssSelector(".gLFyf");
    /*
         1. open the google.com webpage
         2. in search box type query string and submit the search
         3. Verify that result page is showing up
         4. Verify that amount of results is more than 100
      */

    @BeforeSuite
    public void testSuiteSetup(){
        System.setProperty("webdriver.gecko.driver", "src/test/resources/geckodriver");
        driver = new FirefoxDriver();

    }
    @AfterSuite
    public void tearDown(){
        driver.quit();
    }

    @Test
    public void test001() {
        String quarryString ="Portnov Computer School";

        openWebPage();
        searchBoxInput(quarryString);
        searchResultVerify();
        verifyResultsNumber();

        //TODO read about try and catch block
    }

    private void verifyResultsNumber() {
        String[] stringArray = resultsStatsTextValue.split(" ");
        String amountOfResults = stringArray[1];
        String finalAmount = amountOfResults.replace(",", "");
        int amountOfResultsParsed = Integer.parseInt(finalAmount);
        Assert.assertTrue(amountOfResultsParsed > 100);
    }

    private void searchResultVerify() {
            WebElement resultsStatsElement = driver.findElement(resultVerifyLocator);
            resultsStatsTextValue = resultsStatsElement.getText();
            Assert.assertTrue(resultsStatsTextValue.contains("results"));
    }

    private void openWebPage() {
        driver.get(GOOGLE_MAIN_PAGE_URL);
    }
    private void searchBoxInput(String quarryString) {
        WebElement textInput = driver.findElement(textInputLocator);
        textInput.sendKeys(quarryString);
        textInput.submit();
        try {
            sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

}
